spring.application.name=matounso

jwt.secret=BGkifrfgJpmUXcFlp2H2bDesyB8qBesCfX5t3KWhaTk=
jwt.expiration=28800000
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/matounso?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Laddis001$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=MatounsoHikariCP

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.org.springframework.security=DEBUG

